name = "lean_worker"
version = "0.1.0"
defaultTargets = ["lean_worker", "LeanWorker", "LeanWorkerTest"]

[[lean_lib]]
name = "LeanWorker"

[[lean_lib]]
name = "LeanWorkerTest"
globs = ["LeanWorkerTest.+"]

[[lean_exe]]
name = "lean_worker"
root = "Main"

[[lean_exe]]
name = "test_server"
root = "LeanWorkerTest.TestServer"

[[lean_exe]]
name = "test_client"
root = "LeanWorkerTest.TestClient"

[[lean_exe]]
name = "run_tests"
root = "LeanWorkerTest.Main"

[[lean_exe]]
name = "full_server"
root = "LeanWorkerTest.FullServerCli"
